### ISSUE TITLE
regex flags?

### ISSUE THREAD

**Issue by underscorediscovery** [Simn/hxparse#32]
I have been looking for where the regex is handled to see the default flags, but I can't seem to find it.

Secondly, How would I go about matching a /m flag?
This might go against the stream approach, but there are cases where I can't seem to make sense of the parsing - for example, a //comment in a file would require a /m flag for most cases I know of.

Any suggestions?

![screenshot 2015-01-28 21 57 14](https://cloud.githubusercontent.com/assets/236374/5950747/a544dade-a738-11e4-96b2-7e71afdddcc5.png)

**Comment by Simn** [comment]
The m flag in this context only makes sense for ^ and $ which are both not supported. I don't think lexing engines typically have these either because at least ^ is a contextual thing.

As for comment lines, you can simply lex everything that's not \r or \n. For haxeparser I'm using `"//[^\n\r]*"`.

In general I'm not supposed to allowing useful flags, but someone would have to actually implement them in LexEngine.hx.

**Comment by Simn** [comment]
... _opposed_ to allowing...

**Comment by underscorediscovery** [comment]
That makes sense, that's what I had figured but wanted to be sure. 
I'll look at haxeparser for subsequent questions re multi line comments, thanks.

**Comment by danielo515** [comment]
> The m flag in this context only makes sense for ^ and $ which are both not supported. I don't think lexing engines typically have these either because at least ^ is a contextual thing.

Sorry for commenting in an old thread, but then how can you match things that are supposed to be the first thing in the line ? Like documentation comments ?
