### ISSUE TITLE
Investigate ways to implement this without exceptions

### ISSUE THREAD

**Issue by Simn** [Simn/hxparse#44]
hxparse was heavily inspired by how the real Haxe parser works. Unfortunately, OCaml deals with exceptions much better than the Haxe targets do. My initial profiling suggests that we spend way too much time with exception handling.

**Comment by zicklag** [comment]
I've just recently gotten into Rust programming and I really like how Rust manages error handling without exceptions by using a `Result<T, U>` enum type with to variants `Ok(T)`, and `Err(U)`. Each function that can fail has a return type of `Result` and it allows the calling function to handle both success and failure without exceptions. It would potentially be more cumbersome to do in Haxe without Rust's `?` operator for automatically propagating errors, though.

I would think performance shouldn't be a problem, though because it is all handled through the functions' return types.

**Comment by Simn** [comment]
Closing this as I don't plan to spend any time on hxparse.
